#%RAML 1.0 DataType

description: Предложение мастера на заявку
properties:
  id: integer
  commentary: string
  price: string
  date: datetime

example:
  id: 1
  commentary: "Сделаю до завтра"
  price: "500 рублей"
  date: 1970-01-01T00:00:00Z
