#%RAML 1.0
title: Types
Types:
  BaseResponse:
    type: object
    properties:
      status: integer
      error: string
  User:
    type: object
    properties:
      first_name: string
      last_name: string
      phone: string
      email: string
      verification_status: integer

  NewUser:
    type: object
    properties:
      status: integer
      error: string
      token: string
      user: User
