#%RAML 1.0
title: Aladdin
baseUri: https://vsealaddin.ru/api/auth
resourceTypes:
  NewUser: !include types.raml
/confirm_token:
  post:
    description:
    body:
      application/json:
        user_type: integer
        token: string
    responses:
      200:
        body:
          application/json:
            type: NewUser
      201:
        description: |
          Succesfully created a new resource
        headers:
          Location:
            description: |
              Location of the newly created resource
            type: string
            required: false
