#%RAML 1.0 DataType

type: !include BaseResponses.dataType.raml
properties:
  personal:
    description: Заявки, направленные напрямую к мастеру
    type: array
    items: !include ../order/BaseOrder.dataType.raml
  shared:
    description: Общие заявки из пула
    type: array
    items: !include ../order/BaseOrder.dataType.raml
