#%RAML 1.0 NamedExample

/confirm_token:
  post:
    description: Проверка валидности токена авторизации
    queryParameters:
      user_type: integer
      token: !include ../types/Token.dataType.raml
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/UserResponse.dataType.raml

/login:
  post:
    description: Проверка наличия номера телефона в БД
    queryParameters:
      user_type: integer
      phone: !include ../types/Phone.dataType.raml
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.dataType.raml

/register:
  post:
    description: Регистрация нового пользователя
    queryParameters:
      user_type: integer
      first_name: !include ../types/FirstName.dataType.raml
      last_name: !include ../types/LastName.dataType.raml
      email: string
      phone: !include ../types/Phone.dataType.raml
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.dataType.raml

/confirm_sms:
  post:
    description: Подтверждение номера телефона при авторизации
    queryParameters:
      user_type: integer
      phone: !include ../types/Phone.dataType.raml
      code: !include ../types/Code.dataType.raml
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/UserResponse.dataType.raml
