#%RAML 1.0 NamedExample

/confirm_token:
  post:
    description: Проверка валидности токена авторизации
    queryParameters:
      user_type: integer
      token: !include ../types/Token.DataType.raml
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/UserResponse.DataType.raml

/login:
  post:
    description: Проверка наличия номера телефона в БД
    queryParameters:
      user_type: integer
      phone: !include ../types/Phone.DataType.raml
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponse.DataType.raml

/register:
  post:
    description: Регистрация нового пользователя
    queryParameters:
      user_type: integer
      first_name: !include ../types/FirstName.DataType.raml
      last_name: !include ../types/LastName.DataType.raml
      email: string
      phone: !include ../types/Phone.DataType.raml
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponse.DataType.raml

/confirm_sms:
  post:
    description: Подтверждение номера телефона при авторизации
    queryParameters:
      user_type: integer
      phone: !include ../types/Phone.DataType.raml
      code: !include ../types/Code.DataType.raml
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/UserResponse.DataType.raml
