#%RAML 1.0 NamedExample

/login:
  post:
    queryParameters:
      user_type: integer
      phone: string
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.dataType.raml
