#%RAML 1.0 NamedExample

/list_orders:
  description: Получение списка заявок(пул или активные)/истории для мастера
  post:
    queryParameters:
      token: !include ../types/Token.DataType.raml
      order_type: !include ../types/typeOrder.DataType.raml
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/OrdersResponse.DataType.raml
/order:
  description: Получение подробных сведений о заявке
  post:
    queryParameters:
      order_id: integer
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/ConcreteOrderResponse.DataType.raml

/response:
  description: Предложение мастера на конкретную заявку
  post:
    queryParameters:
      token: !include ../types/Token.DataType.raml
      id: integer
      commentary: string
      price: string
      date: datetime
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.DataType.raml

/add_service:
  description: Добавление услуги к заявке
  post:
    queryParameters:
      token: !include ../types/Token.DataType.raml
      name: string
      price: integer
      order_id: integer
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.DataType.raml

/complete_order:
  description: Завершение заявки со стороны мастера
  post:
    queryParameters:
      token: !include ../types/Token.DataType.raml
      order_id: integer
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.DataType.raml

# /add_card:
#   description: Добавление карты пользователя
#   post:
#     queryParameters:
#
