#%RAML 1.0 NamedExample

/list_orders:
  description: Получение списка заявок(пул или активные)/истории для мастера
  post:
    queryParameters:
      token: !include ../types/Token.dataType.raml
      type_order: !include ../types/typeOrder.dataType.raml
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/OrdersResponse.dateType.raml
/order:
  description: Получение подробных сведений о заявке
  post:
    queryParameters:
      order_id: integer
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/ConcreteOrderResponse.dataType.raml

/response:
  description: Предложение мастера на конкретную заявку
  post:
    queryParameters:
      token: !include ../types/Token.dataType.raml
      id: integer
      commentary: string
      price: string
      date: datetime
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.dataType.raml

/add_service:
  description: Добавление услуги к заявке
  post:
    queryParameters:
      token: !include ../types/Token.dataType.raml
      service_name: string
      price: integer
      units: string
      order_id: integer
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.dataType.raml

/complete_order:
  description: Завершение заявки со стороны мастера
  post:
    queryParameters:
      token: !include ../types/Token.dataType.raml
      order_id: integer
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.dataType.raml
