#%RAML 1.0 NamedExample

/categories:
  get:
    description: |
      Получить все доступные категории
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/CategoryResponse.dataType.raml
        description: |
          Succesfully retrieved resource
  post:
    queryParameters:
      token: !include ../types/Token.dataType.raml
      subcategories:
        type: array
        items: !include ../types/SubCategory.dataType.raml
    description: |
      Create a new resource
    body:
      application/json: !!null
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.dataType.raml

/test:
  get:
    description: |
      Получить список вопросов
    responses:
      200:
        description: |
          список вопросов
        body:
          application/json:
            type: !include ../types/responses/QuestionResponse.dataType.raml
  post:
    queryParameters:
      token: !include ../types/Token.dataType.raml
    description: |
      Create a new resource
    body:
      application/json: !!null
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.dataType.raml

/upload_photo:
  post:
    queryParameters:
      token: !include ../types/Token.dataType.raml
      isAvatar: boolean
      isPassport: boolean
      isDocument: boolean
    description: |
      Загрузка фото
    body:
      application/json:
        type: file
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.dataType.raml

/main_info:
  post:
    queryParameters:
      token: !include ../types/Token.dataType.raml
      first_name: !include ../types/FirstName.dataType.raml
      last_name: !include ../types/LastName.dataType.raml
      email: string
      birthdate: date-only
    description: |
      Установка основной информации
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.dataType.raml

/subway_info:
  get:
    description: |
      Получение станций метро
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/SubwayResponse.dataType.raml
  post:
    queryParameters:
      token: !include ../types/Token.dataType.raml
      subways:
        type: array
        items: !include ../types/Subway.dataType.raml
      expirienses: string
      education: string
      about: string
    description: |
      Обновление информации
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.dataType.raml

/about_price_sale:
  post:
    queryParameters:
      token: !include ../types/Token.dataType.raml
      services:
        type: array
        items: !include ../types/Price.dataType.raml
      sales: string
    description: |
      Сохранение информации о мастере, его цен и скидок
    responses:
      200:
        body:
          application/json:
            type: !include ../types/responses/BaseResponses.dataType.raml

/call_time:
  post:
    queryParameters:
      token: !include ../types/Token.dataType.raml
      call_time: datetime
    description: |
      Установка времени звонка
    responses:
      201:
        description: |
          Succesfully created a new resource
        headers:
          Location:
            description: |
              Location of the newly created resource
            type: string
            required: false
