#%RAML 1.0 DataType

description: Базовая заявка, которая будет возвращена мастеру в пул (Не подробная)
properties:
  id: integer
  name: string
  amount: string
  date: datetime
  category: !include ../SubCategory.DataType.raml
  is_safety: boolean
